Repository UXARRAY/uxarray, pull requests merged in 2023-05, with the labels that each got.

#297 Add `Grid._build_face_edges_connectivity`
  docs/internal_api/index.rst
  docs/user_api/index.rst
  test/test_grid.py
  uxarray/grid.py
Labels: bug, enhancement

#315 Create release request issue template
  .github/ISSUE_TEMPLATE/release_request.md
Labels: enhancement, release

#317 CI Update: Drop support for Python 3.7 and 3.8; add 3.11
  .github/workflows/ci.yml
  docs/installation.rst
  requirements.txt
  setup.py
Labels: enhancement

#308 Rename `face_dimension` connectivity to `nNodes_per_face`
  docs/internal_api/index.rst
  test/test_grid.py
  uxarray/grid.py
Labels: enhancement
