Repository UXARRAY/uxarray, pull requests merged in 2023-07, with the labels that each got.

#321 Multiprecision unique coords detection through verts
  ci/docs.yml
  ci/environment.yml
  ci/upstream-dev-environment.yml
  docs/examples.rst
  docs/examples/000-template.ipynb
  docs/examples/005-multiprecision-usage.ipynb
  docs/gallery.yml
  docs/user_api/index.rst
  test/test_grid.py
  test/test_multi_precision_helpers.py
  uxarray/__init__.py
  uxarray/core/grid.py
  uxarray/multi_precision_helpers.py
  uxarray/utils/constants.py
Labels: enhancement, multiprecision

#380 Fix CI failing after `nNodes_per_face` Fix
  test/constants.py
Labels: bug, CI

#371 Numba JIT and Cache Attribute
  docs/user_api/index.rst
  uxarray/core/api.py
  uxarray/utils/constants.py
  uxarray/utils/get_quadratureDG.py
  uxarray/utils/helpers.py
Labels: enhancement

#369 Fix Upstream CI
  ci/upstream-dev-environment.yml
Labels: CI

#372 Multiprecision unique coords detection to `__from_ds__`
  test/test_grid.py
  uxarray/core/grid.py
  uxarray/utils/constants.py
Labels: multiprecision

#370 Organize Helpers and Project Structure
  docs/examples/003-area-calc.ipynb
  docs/examples/004-working-with-mpas-grids.ipynb
  docs/internal_api/index.rst
  docs/user_api/index.rst
  test/test_exodus.py
  test/test_grid.py
  test/test_helpers.py
  test/test_mpas.py
  test/test_scrip.py
  test/test_ugrid.py
  uxarray/__init__.py
  uxarray/constants.py
  uxarray/core/api.py
  uxarray/core/dataarray.py
  uxarray/core/dataset.py
  uxarray/grid/__init__.py
  uxarray/grid/area.py
  uxarray/grid/connectivity.py
  uxarray/grid/coordinates.py
  uxarray/grid/grid.py
  uxarray/io/_exodus.py
  uxarray/io/_mpas.py
  uxarray/io/_scrip.py
  uxarray/io/_ugrid.py
  uxarray/io/utils.py
  uxarray/utils/__init__.py
  uxarray/utils/helpers.py
  uxarray/utils/numba_settings.py
Labels: documentation, enhancement
