Repository UXARRAY/uxarray, pull requests merged in 2023-08, with the labels that each got.

#403 Fix typo in user_api/uxarray_api.md
  docs/user_api/uxarray_api.md
Labels: documentation

#357 Point on GCA helper function
  docs/internal_api/index.rst
  docs/user_api/index.rst
  test/test_helpers.py
  uxarray/constants.py
  uxarray/grid/coordinates.py
  uxarray/grid/lines.py
Labels: enhancement

#410 Fix Upstream CI
  ci/upstream-dev-environment.yml
Labels: CI

#299 Add `Grid.build_node_face_connectivity`
  docs/internal_api/index.rst
  test/test_grid.py
  test/test_helpers.py
  uxarray/grid/connectivity.py
  uxarray/grid/grid.py
Labels: enhancement
