Repository UXARRAY/uxarray, pull requests merged in 2023-06, with the labels that each got.

#325 Improved Access & Representation of UGRID Topology Variables
  docs/internal_api/index.rst
  test/constants.py
  test/test_api.py
  test/test_grid.py
  uxarray/core/grid.py
Labels: enhancement, redesign, high priority

#336 Update Documentation & Clean-Up Code for Redesign
  README.md
  docs/api.rst
  docs/citation.rst
  docs/examples.rst
  docs/examples/001-read-grid-data.ipynb
  docs/examples/001-working-with-unstructured-grids.ipynb
  docs/examples/002-access-grid-info.ipynb
  docs/examples/002-grid-topology.ipynb
  docs/examples/003-area-calc.ipynb
  docs/gallery.yml
  docs/getting-started/freq-asked-questions.rst
  docs/getting-started/overview.rst
  docs/getting-started/quick-install.rst
  docs/index.rst
  docs/installation.rst
  docs/internal_api/index.rst
  docs/quickstart.rst
  docs/user_api/index.rst
  test/test_api.py
  test/test_grid.py
  uxarray/core/dataarray.py
  uxarray/core/dataset.py
  uxarray/core/grid.py
Labels: documentation, redesign, high priority

#350 Version bump to 2023.06.0
  meta.yaml
Labels: release

#250 Working with MPAS Grids Usage Example
  .readthedocs.yml
  ci/docs.yml
  docs/_static/examples/mpas/c-grid.png
  docs/conf.py
  docs/examples.rst
  docs/examples/004-working-with-mpas-grids.ipynb
  docs/gallery.yml
Labels: community support

#364 Fix typos
  uxarray/core/grid.py
  uxarray/io/_exodus.py
  uxarray/io/_scrip.py
Labels: bug
