Repository UXARRAY/uxarray, pull requests merged in 2024-05, with the labels that each got.

#728 Ruff Updates
  .pre-commit-config.yaml
  docs/examples/000-template.ipynb
  docs/examples/001-working-with-unstructured-grids.ipynb
  docs/examples/002-grid-topology.ipynb
  docs/examples/003-area-calc.ipynb
  docs/examples/004-working-with-mpas-grids.ipynb
  docs/examples/005-to-geodataframe-for-holoviz.ipynb
  docs/examples/006-plot-api-topology.ipynb
  docs/examples/007-polygon-viz.ipynb
  docs/examples/008-point-viz.ipynb
  docs/examples/009-subsetting.ipynb
  pyproject.toml
Labels: documentation

#472 User Guide & Documentation Improvements
  docs/_static/examples/grids/cam_se.png
  docs/_static/examples/grids/lat_lon.png
  docs/_static/images/icons/contrib.svg
  docs/_static/images/icons/guide.svg
  docs/api.rst
  docs/conf.py
  docs/examples.rst
  docs/examples/001-working-with-unstructured-grids.ipynb
  docs/examples/002-grid-topology.ipynb
  docs/gallery.yml
  docs/getting-started/installation.rst
  docs/getting-started/overview.rst
  docs/getting-started/quick-install.rst
  docs/getting-started/quick-overview.ipynb
  docs/index.rst
  docs/quickstart.rst
  docs/user-guide/data-structures.ipynb
  docs/user-guide/grid-formats.rst
  docs/user-guide/representation.rst
  docs/user-guide/template.ipynb
  docs/user-guide/terminology.rst
  docs/userguide.rst
Labels: documentation

#788 Move area calc notebook to users guide
  docs/gallery.yml
  docs/user-guide/area_calc.ipynb
  docs/userguide.rst
Labels: documentation

#791 Add CODECOV_TOKEN to ci.yml to fix Codecov uploads
  .github/workflows/ci.yml
Labels: bug, CI

#792 Fix ASV CI Workflow
  .github/workflows/asv-benchmarking.yml
  benchmarks/mpas_ocean.py
Labels: CI

#797 Fix Typos in `README.md`
  README.md
Labels: documentation
