Repository UXARRAY/uxarray, pull requests merged in 2024-03, with the labels that each got.

#709 Fix FutureWarnings in the code and tests
  ci/environment.yml
  test/test_computing.py
  test/test_dataarray.py
  test/test_geometry.py
  uxarray/core/dataset.py
  uxarray/core/utils.py
  uxarray/grid/grid.py
  uxarray/io/_exodus.py
Labels: dependencies

#736 Fix documentation typos
  docs/contributing.rst
  docs/examples/009-subsetting.ipynb
Labels: documentation

#731 Fix CI Failures
  ci/asv.yml
  ci/docs.yml
  test/test_plot.py
  uxarray/grid/grid.py
  uxarray/plot/dataarray_plot.py
Labels: CI
