Repository UXARRAY/uxarray, pull requests merged in 2024-08, with the labels that each got.

#874 Preserve attributes when setting desired longitude range
  test/meshfiles/ugrid/quad-hexagon/grid.nc
  uxarray/conventions/ugrid.py
  uxarray/grid/coordinates.py
Labels: bug

#877 Optimize Face Bounds Computation
  benchmarks/face_bounds.py
  test/test_arcs.py
  test/test_grid.py
  uxarray/__init__.py
  uxarray/constants.py
  uxarray/grid/arcs.py
  uxarray/grid/coordinates.py
  uxarray/grid/geometry.py
  uxarray/grid/grid.py
  uxarray/grid/intersections.py
  uxarray/utils/computing.py
Labels: scalability, run-benchmark

#883 Unpin NumPy, Pandas, ASV, Support Python 3.12, Fix Broken Install Link
  .github/workflows/ci.yml
  README.md
  ci/asv.yml
  ci/docs.yml
  ci/environment.yml
  pyproject.toml
  test/test_helpers.py
Labels: dependencies, CI, run-benchmark

#881 Logo Refresh
  README.md
  docs/_static/images/icons/code.svg
  docs/_static/images/icons/contrib.svg
  docs/_static/images/icons/download.svg
  docs/_static/images/icons/guide.svg
  docs/_static/images/icons/science.svg
  docs/_static/images/icons/tips.svg
  docs/_static/images/logos/h_blue.svg
  docs/_static/images/logos/h_dark.svg
  docs/_static/images/logos/h_light.svg
  docs/_static/images/logos/uxarray_logo_quad_tri.svg
  docs/_static/images/logos/v_blue.svg
  docs/_static/images/logos/v_dark.svg
  docs/_static/images/logos/v_light.svg
  docs/_static/style.css
  docs/_static/theme_overrides.css
  docs/conf.py
  docs/index.rst
Labels: documentation

#890 Fix #889: Remove .values in _slice_from_grid
  uxarray/core/dataarray.py
Labels: run-benchmark

#912 ASV CI Fixes
  .github/workflows/asv-benchmarking-pr.yml
Labels: run-benchmark

#917 Refreshed logos - cleanup
  README.md
  docs/_static/images/logos/h_blue.svg
  docs/_static/images/logos/uxarray_logo_h_dark.svg
  docs/_static/images/logos/uxarray_logo_h_light.svg
  docs/_static/images/logos/uxarray_logo_v_dark.svg
  docs/_static/images/logos/uxarray_logo_v_light.svg
  docs/_static/images/logos/uxarray_temp_logo.png
  docs/_static/images/logos/v_blue.svg
  docs/conf.py
Labels: documentation, improvement

#925 Fix Logo URLs and rephrase Zenodo message text a bit
  CITATION.cff
  README.md
Labels: bug, documentation
