Repository UXARRAY/uxarray, pull requests merged in 2024-01, with the labels that each got.

#643 Bug fix for`gca_const_lat_intersection`
  test/test_intersections.py
  uxarray/grid/intersections.py
Labels: bug

#636 Accurate Basic Math Operators
  ci/environment.yml
  docs/internal_api/index.rst
  test/test_computing.py
  uxarray/utils/computing.py
Labels: new feature, improvement

#649 Fix and Improve Upstream CI
  .github/workflows/upstream-dev-ci.yml
  ci/install-upstream.sh
  ci/upstream-dev-environment.yml
Labels: bug, dependencies, testing, CI, improvement

#652 Update piypi.yaml for trusted publishing
  .github/workflows/pypi.yaml
Labels: CI

#554 Helper face edge connectivity cartesian
  docs/internal_api/index.rst
  test/test_helpers.py
  uxarray/grid/utils.py
Labels: new feature, help wanted

#655 Use `sphinx-autosummary-accessors` for rendering accessors in API
  ci/docs.yml
  docs/conf.py
  docs/internal_api/index.rst
  docs/user_api/index.rst
Labels: documentation

#675 Fix optional args for `dataarray_plot.datashade` call in the accessor
  uxarray/plot/accessor.py
Labels: bug, community support

#684 NSF NCAR branding updates
  README.md
  docs/index.rst
Labels: documentation
