Repository UXARRAY/uxarray, pull requests merged in 2024-07, with the labels that each got.

#831 ASV Benchmarking Pull Request Workflow
  .github/workflows/asv-benchmarking-pr.yml
  benchmarks/asv.conf.json
  benchmarks/quad_hexagon.py
  ci/environment.yml
Labels: CI, run-benchmark

#832 MPAS `face_face_connectivity` parsing
  uxarray/io/_mpas.py
Labels: run-benchmark

#837 Face area bug fix
  uxarray/grid/area.py
Labels: run-benchmark

#838 Add Missing Face Area Notebook to User Guide
  docs/userguide.rst
Labels: bug, documentation

#847 Fix UXARRAY/uxarray#846
  uxarray/io/_ugrid.py
Labels: bug

#844 Update `to_polycollection()`, `to_linecollection` and create Matplotlib Visualization Guide
  benchmarks/asv.conf.json
  benchmarks/mpas_ocean.py
  ci/asv.yml
  ci/environment.yml
  docs/user-guide/mpl.ipynb
  docs/userguide.rst
  test/test_dataarray.py
  uxarray/core/dataarray.py
  uxarray/grid/connectivity.py
  uxarray/grid/geometry.py
  uxarray/grid/grid.py
Labels: run-benchmark

#829 Populate `face_face_connectivity`
  benchmarks/mpas_ocean.py
  ci/environment.yml
  test/test_grid.py
  uxarray/grid/connectivity.py
  uxarray/grid/grid.py
Labels: run-benchmark

#867 Pass coords to new UxDataArray in remap methods
  uxarray/remap/inverse_distance_weighted.py
  uxarray/remap/nearest_neighbor.py
Labels: improvement

#868 HTML Repr for `Grid`, `UxDataArray` and `UxDataset`
  test/test_repr.py
  uxarray/conventions/descriptors.py
  uxarray/core/dataarray.py
  uxarray/core/dataset.py
  uxarray/formatting.py
  uxarray/formatting_html.py
  uxarray/grid/grid.py
Labels: new feature

#870 ASV Benchmarks for Remapping and Tree Construction
  benchmarks/mpas_ocean.py
Labels: run-benchmark
