Repository UXARRAY/uxarray, pull requests merged in 2025-05, with the labels that each got.

#1240 Update "Why UXarray" and "Installation" sections
  ci/docs.yml
  docs/conf.py
  docs/getting-started/installation.rst
  docs/getting-started/overview.rst
Labels: documentation

#1251 Use `isel` in Zonal Average
  test/test_zonal.py
  uxarray/core/dataarray.py
  uxarray/core/zonal.py
Labels: bug

#1252 Ensure cartesian coordinates are normalized when constructing a KDTree
  uxarray/grid/grid.py
  uxarray/remap/utils.py
Labels: bug

#1253 Add `UxDataArray.from_healpix()` and support different face dimensions
  test/test_healpix.py
  uxarray/core/dataarray.py
  uxarray/core/dataset.py
  uxarray/core/utils.py
Labels: improvement

#1256 Update slicing to only update edges when possible
  test/test_cross_sections.py
  uxarray/grid/slice.py
Labels: bug

#1249 Optimize Point in Face Computation
  test/test_geometry.py
  test/test_grid.py
  test/test_point_in_face.py
  uxarray/grid/coordinates.py
  uxarray/grid/geometry.py
  uxarray/grid/grid.py
  uxarray/grid/point_in_face.py
Labels: scalability

#1250 Add section in from_points doc on creating regional grid with boundary points
  docs/user-guide/from-points.ipynb
Labels: documentation
