Repository UXARRAY/uxarray, pull requests merged in 2025-03, with the labels that each got.

#1092 Consistently use Xarray for Grid Reader, Improved Dask Support
  docs/api.rst
  docs/user-guide/parallel-load-ux-with-dask.ipynb
  docs/user-guide/subset.ipynb
  test/meshfiles/ugrid/quad-hexagon/multi_dim_data.nc
  test/test_centroids.py
  test/test_dask.py
  test/test_grid.py
  test/test_healpix.py
  test/test_helpers.py
  test/test_mpas.py
  uxarray/core/api.py
  uxarray/core/dataset.py
  uxarray/core/utils.py
  uxarray/formatting.py
  uxarray/grid/connectivity.py
  uxarray/grid/coordinates.py
  uxarray/grid/grid.py
  uxarray/grid/neighbors.py
  uxarray/io/_esmf.py
  uxarray/io/_exodus.py
  uxarray/io/_fesom2.py
  uxarray/io/_healpix.py
  uxarray/io/_icon.py
  uxarray/io/_mpas.py
  uxarray/io/_scrip.py
  uxarray/io/_topology.py
  uxarray/io/_ugrid.py
  uxarray/io/utils.py
Labels: scalability

#1169 Add spatial hashing
  docs/api.rst
  docs/user-guide/spatial-hashing.ipynb
  docs/userguide.rst
  test/test_spatial_hashing.py
  uxarray/grid/grid.py
  uxarray/grid/neighbors.py
Labels: new feature

#1183 Configure Analytics
  docs/conf.py
Labels: documentation

#1185 Update `environment.yml` to fix ASV PR workflow
  benchmarks/mpas_ocean.py
  ci/environment.yml
Labels: run-benchmark
